### ISSUE TITLE
unicode literal string

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#102]
#### Context
````
# coding: utf-8
# another compatibility issue:
print(u"∇")
```
#### Expected and Desired Behavior (standard python)
```
∇
```
This works on python2.7, python3.4, ipython2.7, ipython3, skulpt, and brython.
#### Observed Behavior (RS)
```
ERROR: Unexpected token string «∇», expected punc «,»
```
#### Workaround
Leave off the u at the front of the string.

**Comment by kovidgoyal** [comment]
I'm not really inclined to fix this. RS does not support b'' (there is no bytes type in javascript) so adding support for u'' seems odd. Not to mention that because these string parsing modifiers can stack in python, supporting them would actually be a fairly invasive change to the tokenizer in RS. Not worth the effort for me -- patches are welcome.

**Comment by hartsantler** [comment]
Kovid is right, 
for something this small, it is not worth big making changes to the tokenizer.
in addition, the `u"string"` syntax was deprecated in Python3.0, and only brought back later to ease transition to Python3.  And, the workaround of removing the `u` prefix, produces more readable code.

**Comment by kovidgoyal** [comment]
Turns out I had to implement string literal modifier stacking for other reasons, anyway. After that adding support for this is trivial: https://github.com/kovidgoyal/rapydscript-ng/commit/3cfdedda99960bba323f448cfd8f76ab19b99bf5
