### ISSUE TITLE
[None]*n

### ISSUE THREAD

**Issue by hartsantler** [atsepkov/RapydScript#103]
It might be worth supporting this syntax, it is not something i often use myself, but i do see it every once in awhile.  The translator could support this as a special case, and translate to `new Array(n)` which allocates an array of size n, where the elements are `undefined`.  Otherwise, it would be good to raise a syntax error, or have a warning in the linter that this is not supported.

**Comment by atsepkov** [comment]
This is a special-case of #45, I'll close this in favor of it. Also, while `new Array(n)` is more efficient, I'm on the fence between that and filling the array with actual nulls, because one produces `[null, null, null, null]` as the user expected, and the other produces `[undefined, undefined, undefined, undefined]`.
