### ISSUE TITLE
Dict value cannot be in a new line

### ISSUE THREAD

**Issue by mozbugbox** [atsepkov/RapydScript#11]
The following code failed to compile with an `ERROR: Unexpected token` error.

``` python
a = {"ke":
        "looooooong string"
    }
```

It seems that the value must be in the same line of the semicolon.

**Comment by kovidgoyal** [comment]
This is fundamentally unfixable with the current design of the compiler. The problem is that the the ':' character is used both to denote the start of a new block and to delineate keys from values. Indentation checking currently happens in the tokenizer and not the parser. The tokenizer has no reliable way to know if ':' mean a new block or end of key. This is the case because object literals can have function as values. 

To fix this would mean moving the whitespace checking into the parser. But that is a pretty invasive change.

**Comment by kovidgoyal** [comment]
Actually, I figured this can be done fairly simply by having the parser modify the internal state of the tokenizer. This is not a clean solution, but it works, and is, as far as I can see the ebst that can be done with the current compiler design.

https://github.com/kovidgoyal/rapydscript-ng/commit/880e38fbcb2fa97edc44378d2ee9b2b07a94c910

**Comment by atsepkov** [comment]
If I remember correctly, I already used a similar hack elsewhere - it was also to treat the state within a dictionary differently than within a regular block (although this may have been in original version of RapydScript). Also, you may have already addressed this (I haven't had a chance to look at your code), but beware of functions nested within the dictionary:

    def():
        # normal indentation rules apply
        a = {
            # special indention rules
            "b":
                def():
                    # normal indention rules again
                    ...
            # special indentation rules
        }

**Comment by kovidgoyal** [comment]
Yeah functions as dictionary values are the reason the hack becomes necessary in the first place :)

**Comment by atsepkov** [comment]
This is now partially fixed, only the first key now throws this error. Don't remember which commit addressed it, but the code is now using a similar trick to Kovid's version - so I'm confused why it doesn't work when the split key appears in hash first.
