### ISSUE TITLE
Reference error bug?

### ISSUE THREAD

**Issue by araichev** [atsepkov/RapydScript#110]
Hi there,

Firefox 42.0 for Linux doesn't like some compiled RapydScript.
Here is an example.
When i compile this RapydScript code

    s = [[1, 2], [3, 4], [5, 6]]
    t = [i for i, j in s if j == 4]
    alert('t =', t)

using the RapydScript 0.3.9 compiler and paste the single line of JavaScript output into Firefox's web console, i get the result 

    ReferenceError: assignment to undeclared variable PO_Unpack

Is this because the RapydScript compiler is not inserting a necessary ``var``?

**Comment by atsepkov** [comment]
Yep, here is what it's compiling to:
~~~
var t;
t = (function() {
    var ՐՏ_Iter = ՐՏ_Iterable(s), ՐՏ_Result = [], i, j;
    for (var ՐՏ_Index = 0; ՐՏ_Index < ՐՏ_Iter.length; ՐՏ_Index++) {
        ՐՏ_Unpack = ՐՏ_Iter[ՐՏ_Index];
        i = ՐՏ_Unpack[0];
        j = ՐՏ_Unpack[1];
        if (j === 4) {
            ՐՏ_Result.push(i);
        }
    }
    return ՐՏ_Result;
})();
~~~
Unpack should receive its own `var`, you're seeing the problem in your console probably because you're running in strict mode, otherwise it would be appended to global scope. Most of the modules RS generates are also strict, so I'm not sure how this was working beforehand unless something else declared Unpack in same or higher scope.
