### ISSUE TITLE
Problem with Keyword Arguments

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#112]
I am using a clone of the github repository updated only a few days ago.

I have a class called Helper which has a show method

`     def show(self, sender, options);
             #etc.`

show expects options to be an object, either empty or with a number of attributes. It checks for the existence of specific attributes and takes appropriate action if it finds them. 

self.helper is an instance of Helper and I call its show method thus, for example,

`     self.helper.show(sender, align='BLTR', htmltext='This is some help text')`
That compiles to 
`     kwargs(self.helper.show).call(self.helper, sender, {align: "BLTR", htmltext:'This is some help text'});`
That fails in self.helper.show with options undefined.

 However, if I just remove the kwargs call, leaving
`     self.helper.show.call(self.helper, sender, {align: "BLTR", htmltext:'This is some help text'});`
options come through as an object with the correct attributes and values. But the use of call is redundant so 
`     self.helper.show(sender, {align: "BLTR", htmltext:'This is some help text'});`
would be even better.
At no point have I deliberately invoked the @kwargs decorator and if I redefine kwargs to just return the function it is applied to, everything works fine. All the compiler needs to do is stuff the keyword arguments into an object and it has done that perfectly well and then ruined its good work by wrapping it in the kwargs call.

Have I misunderstood something?

**Comment by atsepkov** [comment]
So the kwargs decorator overwrites the positional arguments in function definition itself. The idea behind it handling the case where your show() method takes in align and htmltext arguments directly (see `test/kwargs.pyj`). Your case sounds like a variant of the commented out `sub2` test case. Unfortunately the compiler is not able to detect the last argument as kwargs type without the **, otherwise it would have complained that this case isn't handled. I don't remember my reason for not simply passing kwargs as the last argument, maybe it was because I had no good way of checking that the number of arguments aligns?

**Comment by atsepkov** [comment]
Just checked kwargs logic, I was popping the kwargs argument in the function, but don't think there was a good reason for me doing so, so I tweaked the logic to keep it on. I think that should fix your use case. I've re-enabled the `sub2` test after removing ** from it and created `sub3` for that purpose instead, when the time comes to implement it.

**Comment by jpcharlesworth** [comment]
@atsepkov, nice to see you back and thanks for looking at this issue. The minor tweak you mention above does indeed seem to fix my use case, so thanks for that.
