### ISSUE TITLE
how to use mixin ?

### ISSUE THREAD

**Issue by mardon86** [atsepkov/RapydScript#114]
I wrote the code like this, but it doesnt work
```
class Flyable:
  def __init__(self):
    pass
  def fly(self):
    print("flying...")

class Quackable:
  def __init__(self):
    pass
  def quack(self):
    print("quack!!")

class FlyingDuck(Flyable):
  def __init__(self):
    Flyable.__init__(self)

mixin(FlyingDuck, Quackable)

flyingduck = FlyingDuck()
flyingduck.fly()
flyingduck.quack()
```
Result :
flying... 
TypeError: flyingduck.quack is not a function

**Comment by atsepkov** [comment]
The `mixin` method isn't often used, so I wouldn't be surprised if it broke since it was implemented. From the look of it, you're using it correctly, but try passing a boolean to it as last argument as mentioned in https://github.com/atsepkov/RapydScript#classes (the boolean tells it whether to override methods or not). If that doesn't work, the bug is probably something silly since there isn't much logic in the `mixin` function anyway (loop through the prototype, pick up all "own" properties, and attach them to the new object if they don't already exist).

**Comment by mardon86** [comment]
I tried to pass True as the last argument, but still doesnt work. 
I looked at the output code of Quackable class:
```
function Quackable() {
    Quackable.prototype.__init__.apply(this, arguments);
}
Quackable.prototype.__init__ = function __init__(){
    var self = this;
};
Quackable.prototype.quack = function quack(){
    var self = this;
    alert("quack!");
};
```
and your mixin implementation is:
```
function ՐՏ_mixin(target, source, overwrite) {
    for (var i in source) {
        if (source.hasOwnProperty(i) && overwrite || typeof target[i] === "undefined") {
            target[i] = source[i];
        }
    }
}
```
Cmiiw, i think the mixin implementation should be not only targetting the own property, but also targetting the prototype, because the quack method is in the prototype. Am i right ?

**Comment by atsepkov** [comment]
Good catch, it should actually only be targeting the prototype, although I guess there couple be class variables on the object as well. With that in mind, the method should be rewritten as follows:

    function ՐՏ_mixin(target, source, overwrite) {
        for (var i in source) {
            if (source.hasOwnProperty(i) && overwrite || typeof target[i] === "undefined") {
                target[i] = source[i];
            }
            if (source.prototype.hasOwnProperty(i) && overwrite || typeof target[i] === "undefined") {
                target.prototype[i] = source.prototype[i];
            }
        }
    }
