### ISSUE TITLE
String Repetition Operator no longer acceptable

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#121]
As of a recent commit, the code below causes a compiler error

    record['Days'] = 'F' * count    # where count is an integer

produces
ERROR: cannot perform binary '*' operation on incompatbile elements of type String and Number

**Comment by atsepkov** [comment]
And in the previous version, wouldn't this operation just result in `NaN` or am I missing something? I don't think I ever added anything to handle that operation in RapydScript and don't believe any JavaScript engines actually clone the string using that operation.

**Comment by atsepkov** [comment]
Just to clarify, this assertion is intentional. Previously this was a silent bug and I'm in the process of making compiler catch as many of them as I can early on. There is no good way of correctly resolving `* N` across the board, so it would be dangerous to compile it into something else. In this case the compiler figured out that `count` is an integer, but in some cases it may not. I would rather have the user be aware that they need to use a different approach all the time than have them deal with a very devious bug 20% of the time when compiler can't resolve it and JS ends up computing it to NaN. Most recent browsers allow this alternative instead:

    record['Days'] = 'F'.repeat(count)

And if you need to support older ones you can either set up a list comprehension or do this:

    record['Days'] = Array(count+1).join('F')

Is that good enough for your use case?

**Comment by jpcharlesworth** [comment]
You are quite right, it did evaluate to a NaN. The reason it never showed as an error is that this initial value is always overwritten elsewhere in the code. This application has a long history, having been ported from Pyjamas where the string repetition operator was supported, I think.

Thanks for the explanation of why it has shown up now and I entirely agree with your approach to catching silent bugs. Although the line of code is really redundant, I will try your suggested fixes because I may want to do something similar in future.
