### ISSUE TITLE
Supporting JS-keyword  'const'

### ISSUE THREAD

**Issue by valq7711** [atsepkov/RapydScript#126]
ES2015  has a notion of const
`const MY_CONSTANT = "some-value";`
of course, I know workaround `JS('const  MY_CONSTANT = "some-value"; ' )  `
but it would be nice to be able to declare constants  in RS

**Comment by atsepkov** [comment]
I have thought about this as well, as marking a variable as a constant is useful. Problem is that I really don't like introducing new keywords, and while `const` by itself may not be the end of the world, it sets a precedent for `let` and possibly others JavaScript may introduce in the future undermining the way scoping works in RapydScript altogether.

So one option would indeed be to introduce `const` as a keyword and continue fighting off the `let` guys, which will likely use this same argument, although the concept of `let` makes less sense in a language with inverted scope like RS/Python.

Another option that I'm thinking about, may upset some purists but may be more in the spirit of Python, compile every UPPER_CASE variable into a `const`, effectively raising errors for users attempting to do this:

    GLOBAL = 'foo'
    def func():
        nonlocal GLOBAL
        GLOBAL += 'bar'

**Comment by valq7711** [comment]
Thanks for your reply!
Converting   UPPER_CASE variable into a `const` sounds good!, it could be just  a compiler option argument or something like python directive `# -*- coding: utf-8 -*-`.

**Comment by kovidgoyal** [comment]
Please do not make UPPER_CASE variables const. That will make it unneccesarily harder to port existing python code to RS. Which is one of the major use cases of RS. And putting it behind a compiler flag just means that you make it harder to copy RS code from one place to another, since whether it works now depends on what compiler options are used to compile it. That kind of tradeoff is not worth it for something as marginally useful as const variables. I have written over a million lines of python and never felt the need to use const variables even once. 

As for supporting javascript storage modifiers like const/let/etc. you will have a very hard time getting the scoping rules right. Remember that const changes the scope of variables in JS. You will end up with a language that has some weird hybrid of the scoping rules of python and JS which will just lead to user confusion.

Just because a feature exists in JS is *not* a sufficient reason to add it to RS.

**Comment by valq7711** [comment]
OK guys, I see you've thought about it a lot. In fact, I never felt the urgent need to use `const`. 
I just thought that it could improve js-performance, if it isn't so - let it remain as is, considering that there is short workaround.
