### ISSUE TITLE
Cannot use underscore.js

### ISSUE THREAD

**Issue by mardon86** [atsepkov/RapydScript#129]
I'm using the newest rapydscript version and using it on browser with underscore.js, but it resulting ReferenceError when i'm trying to access '_'
It works fine if i'm using version 0.5.35 (the one before you refactor your code)
thx.

**Comment by atsepkov** [comment]
Can you give an example code sample that's causing this? If I can see the actual code I can often troubleshoot issues much faster.

**Comment by mardon86** [comment]
```
<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='initial-scale=1.0, maximum-scale=1.0, user-scalable=no'><script src='rapydscript.js'></script><script src='underscore.js'></script></head><body>
<!--------------------------------------------------------------------->


<h1>Hello World</h1>


<!--------------------------------------------------------------------->
<script id='rs_code' type='text/python'>
#-----------------------------------------------------------------------


state = 0
document.getElementsByTagName('h1')[0].onclick = def(ev):
    nonlocal state
    if state == 0:
        ev.target.style.backgroundColor = 'red'
        ev.target.style.color = 'white'
        state = 1
    else:
        ev.target.style.backgroundColor = 'white'
        ev.target.style.color = 'black'
        state = 0


template =\
'''
<p>Hi, my name is <%=name%>, i'm <%=age%> years old.</p> 
'''

data = [
    {name: 'Jean', age: 30},
    {name: 'Jane', age: 29},
    {name: 'John', age: 24}
]

for i in data:
    d = document.createElement('div')
    d.innerHTML = _.template(template)(i)
    document.body.appendChild(d)


#-----------------------------------------------------------------------
</script><script id='rs_out'></script><script>document.getElementById('rs_out').innerHTML = rapydscript.compile(document.getElementById('rs_code').innerHTML, {private_scope: false, beautify:true});</script></body></html>
```

ReferenceError: _ is not defined

**Comment by atsepkov** [comment]
It's been a while ago, but if I remember correctly part of what the refactor did was making strict mode more consistent. It sounds like you're experiencing this issue: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined

So somehow the call to `_.template` is being evaluated before underscore.js defines `_`. Since your code is compiled later than the include that shouldn't be an issue. Are you sure underscore is being loaded? Is it accessible from JS itself?

**Comment by mardon86** [comment]
The ReferenceError only appear if i put the rapydscript.js before underscore.js, otherwise is fine. Somehow
the underscore.js is trying to use/modify something that already been used by rapydscript. and maybe unfortunately rapydscript made it non-writable, so that underscore.js failed to evaluate certain operation that made it failed to create the _ object. 
Honestly i don't know the exact cause, but i wish this can be used as a consideration.

**Comment by atsepkov** [comment]
Hmm, so RapydScript probably redefines a function that underscore itself defines, although why underscore prefers the more global version of that function is beyond me. Unless told otherwise, RapydScript wraps the code it compiles in a self-executing function, which should be enough of a safety. However, for compilation of the compiler itself I disabled that because the compilation functions are meant to be exposed, and rapydscript is meant to be called by itself rather than in a browser along with multiple other libraries. So you're running into this issue because you're using RapydScript in unorthodox way. I should be able to fix the issue by doing the following:

- wrap self in self-executing function as well, the way I do it to all other code
- append all functions that are meant to be exposed to `window || global` object
