### ISSUE TITLE
Unicode characters in output

### ISSUE THREAD

**Issue by Darker** [atsepkov/RapydScript#131]
I know that unicode characters are valid in javascript variable names, but I don't like them very much. Is there an option to have them replaced by `_` for example?

**Comment by atsepkov** [comment]
There is, it's called `RAPYD_PREFIX` in src/utils.pyj, but I haven't done a good job pulling all references out (especially since some are used as function names so they have to be constant) so replacing it just there may break some things, especially in baselib. If you have a better idea of how to refactor it (while still maintaining ES5 support - so ES6 computed names wouldn't be allowed), I'd appreciate the fix.
