### ISSUE TITLE
for loop off by 1

### ISSUE THREAD

**Issue by chuckup** [atsepkov/RapydScript#18]
With this code:
```
for n in range(5):
    print (n)

print ('n should be 4:', n)
```
I get this output:
```
0
1
2
3
4
"n should be 4:",5 
```
Rapydscript generates this code:
```
for (n = 0; n < 5; n++) {
    _$rapyd$_print(n);
}
_$rapyd$_print("n should be 4:", n);
```
It does not matter if I "include stdlib" or not.

But, everything works as expected if I do this:
```
for i, n in enumerate(range(5)):
    print (i, n)

print ('n should be 4:', n)
```
In this version, Rapydscript uses the stdlib range() function

**Comment by atsepkov** [comment]
Hmm, rather than fixing this I think I'll have the linter prevent this usage. Using loop-specific variables outside of a loop is poor design - and in fact not possible in many other languages including perl (and soon won't be possible in native JavaScript with the addition of `let` keyword). If you need to access the variable after the loop terminates, better technique is to copy the value to another variable before loop finishes.
