### ISSUE TITLE
rapydscript on pypi.org

### ISSUE THREAD

**Issue by Tset-Noitamotua** [atsepkov/RapydScript#190]
Does https://pypi.org/project/rapydscript/ relate to this project?

seems outdated, mentions your name, is confusing, should be removed :)

**Comment by atsepkov** [comment]
It is related, but not the same thing. Initially, RapydScript started as small Python project for parsing my old Pyajamas code into JavaScript. Charles was a friend who helped me with it, since he had his own code that needed similar porting. We published this as a pip package, but have since moved away from that implementation because it was slow and fragile.

The current version of RapydScript is a complete rewrite. I'm ok with removing the pip repo if @charleslaw  is.

**Comment by Tset-Noitamotua** [comment]
Thank you for clarification. :+1:
