### ISSUE TITLE
append method does not compile to js push method

### ISSUE THREAD

**Issue by issadarkthing** [atsepkov/RapydScript#208]
Rapydscript:
![image](https://user-images.githubusercontent.com/50593529/66271930-35641280-e896-11e9-84ec-1495c9e5d6af.png)

Javascript(compiled):
![image](https://user-images.githubusercontent.com/50593529/66271951-5cbadf80-e896-11e9-8337-c6c9a8ac14ce.png)

**Comment by valq7711** [comment]
This is not a bug, this is the expected behavior. In the general case, it is impossible to determine whether `append` should be compiled into` push` or `append` is just a custom method of some object, which should be processed as is.
There are `stdlib.pyj` and `stdlib2.pyj` (see  `src/lib`) - the first injects some methods into the prototypes of js-base types  (it is not perfect way and could cause issues if you use third party libs that do the same), the second one exposes python-like classes  - `list` and `dict`  that is safer but not so universal. Both libs have a very short code base, so you need a couple of minutes to get what they  do. To use any of them - just import it. 
As for me - I prefer js-native methods, it's a little bit more verbose,  but code is more stable,  less ambiguity and easier to debug.
