### ISSUE TITLE
Syntax highlighting for TextMate

### ISSUE THREAD

**Issue by akittas** [atsepkov/RapydScript#33]
Hi is it possible to get syntax highlighting in a Textmate bundle for Rapydscript? I really want to use Rapydscript but syntax highlighting is important, and I wanna use it in PyCharm and IntelliJ which are compatible with Textmate bundles.

**Comment by atsepkov** [comment]
I'm pretty sure it's possible since most editors today allow configurable syntax highlighting. With that said, I do not use this editor myself (my editor of choice is vim, and I published my rapydscript config for it here: https://github.com/atsepkov/vim-rapydscript) and since this is not a core feature of the language itself, this would be a lower priority task that hopefully someone from the community using TextMate tackles instead.

One thing to note is that tricking the editor into thinking RapydScript is Python is usually enough (or at least will get you 95% there). A quick google search for "textmate python syntax highlighting" brought me to this, which may be a good starting point if you want this plugin: https://github.com/textmate/python.tmbundle

**Comment by akittas** [comment]
Thanks for the answer, the TeΧmate bundle offers Python syntax highlighting already present in PyCharm and IntelliJ, I guess if the syntax of Rapydscript is similar to Python it will work for most of the stuff.
I was just thinking about a TextMate bundle, as PyCharm, IntelliJ and other editors already support TextMate bundles, while the vim bundle can only be used by Vim and unfortunately is not compatible with other editors. I'm sure it would increase visibility for RapydSript.
But I totally understand this is not a priority, and thank so much for the wonderful RapydScript! After 3 days of despair dealing with JavaScript and CoffeeScript, I found RapydScript and am so relieved!

**Comment by akittas** [comment]
Closing the issue, as it's probably relevant to a separate project
