### ISSUE TITLE
Easier override of regular js functions (namespacing python functions)

### ISSUE THREAD

**Issue by wolfv** [atsepkov/RapydScript#51]
This is an enhancement proposal.

I would like to use `str.split()` in my RapydScript code but it collides with `String.split` (the js equivalent) which otherwise doesn't behave in the same way. This makes it difficult to overload.

Therefore, I would like to ask if it would be possible in a future version to:
1. Export python functions in their own namespace to JS (e.g. `String.py.split` would be the python splot function)
2. automatically use `String.py.split` from all RapydScript code (e.g. hold an array of all overloaded/available functions in the RapydScript parser and then use them accordingly

I know that this might be not entirely in the spirit of keeping RapydScript as a light layer on top of js. I think, however, it does not add any "magic" and is quite transparent.

It might also be cool for operator overloading where you could check during the parsing if the object contains and **add** method etc.

Probably it would need a two-stage parsing process to be successful?

Best,

Wolf

**Comment by atsepkov** [comment]
Part of the problem is duck-typing nature of JS/RS. Just because you see `a.split()` in the code, doesn't mean you're dealing with a string. In that context `a` could be a string, or some class named `Loot` that you're `split`ting with a friend. Compiler needs more information to do this operation without screwing things up for developers. There is no reason, however, stdlib can't overload `String` in this way (there are two versions of stdlib, one that modifies string, another creates a new class that inherits from it - the 2nd is less destructive but you'll have to declare strings as `str('hello world')`).

**Comment by kovidgoyal** [comment]
1. Is implemented in my fork, you can do str.split(a) and the same for all python's builtin string functions including format()

2. @atsepkov the way to do this, is to create a new access operator for compile time function mangling. So the compiler would translate

a->split() to str.split(a)

And the compiler can maintain an internal list of all such functions to be overriden.

However, I am not convinced that 2 is really worth it. It saves only two characters of typing, at the cost of adding a new operator.
