### ISSUE TITLE
New Iterable style breaks jquery etc.

### ISSUE THREAD

**Issue by wolfv** [atsepkov/RapydScript#60]
The new iterable breaks compatibility with jQuery

ie.

```
for el in $('a'):
    print(el)
```

will iterate over the strings: 

```
0: "0"
1: "length"
2: "prevObject"
3: "context"
4: "selector"
```

which, of course, is not desired.

**Comment by atsepkov** [comment]
Sigh... kept trying to figure out what was happening since the following works as expected:

    a = ['one', 'two', 'three']
    for i in a: print(i)

As usual, the problem/hackery is on jQuery's end. jQuery is a convenient library, but it breaks good practices left and right in its implementation.

In this case jQuery claims to return an array of DOM objects, which is BS. What it actually returns is a hash of DOM objects with keys corresponding to array indexes and `.length` attribute. It also appends  extra garbage to the hash - which is the extra properties you're seeing (in other words it assigns enumerable properties, ignoring the JavaScript standard that says otherwise: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty). Try the following:

    $('a') instanceof Array // false
    Object.getOwnPropertyNames($('a')) // will show all of irrelevant attributes because jQuery doesn't mark its extra properties as enumerable: false
    Object.keys($('a')) // same as above

The saving grace that made iterating work with them before was the presence of `length` property. I do not want to go back to relying on it since it will break normal hashes, which have been declared correctly. Imagine the following code, for example:

    box = {
        width: 100,
        height: 50,
        length: 200,
    }
    for dimension in box:
        ...

I do not want to break this proper use case in favor of jQuery's hack. There are a few workarounds here that are possible, however (some on RS's end, some on user's). Here is what the user can do now instead (with 2nd use case probably being the cleanest):

    $a = $('a')
    for i in $a:
        el = $a[i]
        ... do stuff with el

    for k, el in enumerate($('a')):
        ... do stuff with el

    $('a').each(def(i, el):
        ... do stuff with el
    )

And here is a possible hack I can do to sidestep it without hurting hash key iterations:
- Inside `Iterable` function, check if `length` property exists
- If yes, check if keys named range(0, a.length) exist
- if both are met, iterate it like array

Before I'd be comfortable with this, however, I'd want to make sure it will have no side-effects for those not wishing this.

**Comment by wolfv** [comment]
thanks for your time! i just investigated a bit myself, and neither jQuery nor the querySelector seem to work with the ECMA 6 for .. of iterator so I guess it's only fair if it also doesn't work in RapydScript...

**Comment by atsepkov** [comment]
Will `enumerate()` (which doesn't bother checking that passed in structure is array and just traverses it) be good enough or do you want me to investigate the hack in `Iterable` I described above?

Admittedly, part of the problem here is that RapydScript's convention is more aimed at proper inheritance, whereas jQuery's goal was to create a lightweight structure (jQuery is not aimed at enabling developers to write maintainable code, but at getting JS out the door fast). Ideally their return structure should really be inheriting from `Array`.

It's possible I may need to tweak RapydScript to be compatible with ES6 iterators in the future as well, and I'd rather have ES6 dictate RapydScript's function than jQuery - for future compatibility.

**Comment by wolfv** [comment]
I think it's ok for me at the moment :+1: 

Actually I saw this cool idea on a HN thread about rapydscript:
Instead of compiling to JS 5, compile to JS ECMAScript 6 and then use Babel.js to make it usable for everything else. I think that would actually be a pretty cool idea and it might lower the amount of conversion that needs to be done by Rapydscript.

Cheers,

Wolf
