### ISSUE TITLE
Improve the module/import system

### ISSUE THREAD

**Issue by kovidgoyal** [atsepkov/RapydScript#66]
First, let me thank you for the work you have already done. RapydScript is just what I was looking for. And apologies for the long winded post below.

I would like the module/import system to be more like python. I am sure you are already familiar with this, but for my own clarity, I list some problems with the current implementation below. 

 1. If you create a module without a ```module name:``` decoration importing it imports all its symbols into the global namespace of the "main" module. This is unworkable for a large codebase.

 2. If you use ```from x import y``` and y uses ```module something:``` you are left with
var something={y:whatever}
instead of var y = something.y

 3. The use of the ```module:``` is pointless and confusing, it causes imports to be bound to the name from the ```module:``` directive instead of the name used in the local import statement. And it means that all code has to be at at least one level of indentation. Instead all modules should be imported once, but bound into the namespace of the module doing the importing using the names defined by the import statement. So ```import os.path``` should result in ```var os = {path:<all symbols from path module>}``` **not**  ```var name_from_module_declaration = {...}```

 4. There is no support for aliasing (i.e. import x as y)

I am willing to do the work to fix these issues and make the import system work like python. Basically, there would be a global (global to the main modules' scope) variable called ```_$rapyd$_modules``` (corresponding to sys.modules in python) which contains all imported modules. 

Actual ```import``` and ```from import``` statements will be converted into

```js
var x = _$rapyd$_modules[whatever].whatever
```
so that those names are bound only in the local scope of the module doing the importing. 

The problem is these changes are not backwards compatible, and I dont know if this is a direction you are willing to move in. If you are, then I will try to do the work in way that makes it easy for you to merge, if not, I will proceed with an incompatible fork. 

It may be that there is some reason for the current design of the import system and what I am proposing is not feasible, after all, I am a noob at RapydScript. If so, I would appreciate it if you would let me know, to save me the trouble of discovering it on my own :)

**Comment by kovidgoyal** [comment]
I have a working first implementation that mirrors python's import system, with packages being directories containing ```__init__.pyj```. It only imports symbols into the local namespace that are explicitly mentioned (I decided not to implement from x import * as I consider it an antipattern, but if needed it can be done easily).

There are probably bugs and corner cases I have not thought of and tests have to be added. I also got rid of the module keyword and all the code for trying to guess when to automatically insert a new operator. I dont see how that code can possibly be made robust, since one could, for instance, pass in the class as a function argument. Then there is no way for the compiler to know that the function argument is actually a class. 

Instead, I think it is better to just insert new for known javascript class names and classes marked as external. For RapydScript created classes, simply have output.pyj add code in the constructor to detect when when it is being called without new and do the right thing. Once can use the es6 Symbol to do this efficiently (with a simple polyfill for older browsers). 

Currently the code is still in a form where I can generate a pull request easily, let me know if you are willing to consider this approach, or not.

**Comment by kovidgoyal** [comment]
Full implementation, with tests, committed: https://github.com/kovidgoyal/RapydScript/commits/modules

In particular: https://github.com/kovidgoyal/RapydScript/commit/cd116692605892af4c8d4dd8b71bd554b1b2d202

Still waiting to hear whether this is something you are willing to accept.

**Comment by atsepkov** [comment]
Hi Kovid, I apologize for not having the time to take a look at this yet, but please realize that it has only been one day since you posted this, please be patient. I have a full-time job and several side projects.

You're proposing a major change that requires me to study my own use cases as well as those of others. The import structure RapydScript currently uses is not perfect, and I would like to address that. However, one thing to keep in mind is that the Python user is not the only use case. JavaScript's in-browser import structure is in fact of "throw everything in one namespace" type - which has encouraged several usage patterns from the community incompatible with Python's way of importing, I tried to compromise between those to make things convenient from Python and JavaScript point of view.

I won't be able to give this issue the attention it deserves until the weekend, however, please take a look at `--namespace-imports` compile flag as well, since its original purpose was to do this very same thing (although I haven't been testing it, so it's possible it's not functioning well). I'm not opposed to defaulting to use of namespaces, I just want to also make it convenient for those wishing to avoid them (module keyword seemed like a decent compromise).

As far as the `new` keyword, that's a whole other topic, with its own can of worms - that should be discussed in a different issue (or in our google group: https://groups.google.com/forum/#!forum/rapydscript).

**Comment by kovidgoyal** [comment]
No worries, take your time. This is a big decision for you and it deserves careful consideration. I just want to know if you are open to the idea, not your final word on it.

As for JavaScript being everything in one namespace, that is considered to be an antipattern by pretty much any seasoned JS developer. Just see all the work that is being done on AMD, in fact, the recently finalized ES 6 standard for javascript has its own module syntax: http://www.2ality.com/2014/09/es6-modules-final.html

And let me emphasize, with my changes, RS still generates a single big JS file, it's just that the namespaces of individual modules are not polluted. Every module will contain only those symbols explicitly imported by it (and of course everything in the outermost scope -- but that is unavoidable). As such, my changes are orthogonal to ```--namespace-imports```. 

Dont worry about ```new```, I ended up preserving the current behavior of RS, for backwards compatibility, and because while ```new``` can be fixed, ```staticmethod``` and calling baseclass functions cannot. 

Finally, just so you know, I intend to do a fair bit more work on RS while it is still fresh in my mind -- currently I am thinking of:

1) Fixing function calling to have the same semantics as python so you can mix variable number of args, kwargs and positional args in a single function, without using a decorator

2) Writing a pyflakes style unused/undefined reference checker

3) Finishing up my REPL

Unfortunately, it is not efficient for me to do this work on the current state of RS master, so I will be doing it on my fork. That means you will have a tough time merging the other changes if you decide to refuse the import system, I'm sorry for that, but...

**Comment by atsepkov** [comment]
I agree, I also want to emphasize that the purpose of the `module` keyword was exactly to prevent that anti-pattern (you just chose a more Python-like solution to it). As mentioned earlier, the reasoning for explicit keyword rather than implicit namespace as in Python was to avoid surprises in JavaScript world (yes, one may be considered better, but if the new user is not willing to overcome the barrier to entry and if native JS makes it easier to hit the ground running, the system does more harm than good).

I still don't follow why this is orthogonal to `--namespace-imports`. It may not be as polished, but the purpose of it was exactly as you describe, to both wrap each file in its own module and avoid exposing logic to a module that wasn't explicitly imported by it.

Lastly, one of the main goals of RapydScript was to bring the beauty of Python to JavaScript without sacrificing performance, as many predecessors (such as Pyjamas) failed due to their excessive emphasis on Python purity. Seemingly negligible tweaks like wrapping binary operations in an extra function call to allow operator overloading (`a + b -> __add__(a, b)`) or binding function to the object automatically (as Python does) have been tested to snowball into huge performance penalties when the logic is repeated hundreds of times (there are a couple threads on our mailing list with me testing this and subsequently reverting the changes). While on the surface wrapping the module in an extra function call by default seems cheap, I want to make sure I'm not causing that same performance overhead here in case of dozens of nested imports (it sounds like less of an issue here if module logic is only executed once) - or at least have a way for the user to opt-out of this on a per-module basis (perhaps a `dump` keyword to perform the anti-pattern version of the import).

Also, I actually would like support for `from` imports, which would just be syntax sugar for regular import followed by `var a = module.a;` in local module scope.

**Comment by kovidgoyal** [comment]
Module code is only ever executed once, regardless of nesting or how many times a module is imported. As such performance impact is likely not measurable.

My changes support ```from``` imports in exactly the same way as they work in python (I still have to implement aliasing via as).

**Comment by hartsantler** [comment]
How do you call a function in a module from JavaScript?
```javascript
rapymodule.myfunction();
```
above is nice makes interop with hand written js easy. 
It would suck if we have to do:

```javascript
_$rapyd$_modules.myfunction();
```

Inorder to interop well with other transpilers like CoffeeScript, and handwritten JS, there should be an option to pollute the global namespace?

**Comment by kovidgoyal** [comment]
```
from mymod import myfunction

myfunction()
```
That's a lot nicer than mymod.myfunction, if you have to call the function more than once. Indeed, this was one of my motivations for making this change in the first place. 

If there is enough demand, I can even implement ```from mymode import *``` though IMO that is a really bad idea.

**Comment by kovidgoyal** [comment]
Another thing the new import system enables is incremental compilation. The results of compiling a module can be cached on the filesystem with a sha1 signature. So the next time you run rapydscript and the module is imported it will only need to be re-compiled if changed. Currently on my dev machine compiling 10,000 lines of code takes about a second. Assume you split up the code-base into 20, 500 line modules, then the cycle of edit one module-compile-run will go from 1 second to 0.05 seconds. This is almost as good as the edit-run cycle of working on a python codebase, provided you setup some kind of file watcher to auto restart your development server on file changes (which most server frameworks already have). 

Of course, this assumes I actually get around to implementing the incremental compilation :)

**Comment by atsepkov** [comment]
Cool, I like the caching feature (it's similar to Python creating pyc files), as long as users can still choose to do a full rebuild by blowing away these temporary files.

Also, I'm ok with namespaces being the default imports (if you look at my own code, I often use modules anyway), but I still want something that dumps into global namespace (either `dump` keyword or the `from ... import *` statement you mention above). It may be an anti-pattern, but it's often exploited in JS for convenience. Even the fact that you can say `$('div.selected')` as opposed to `jquery.$('div.selected')` is a result of that very same anti-pattern. However, html has its own way of making that happen without the help of RapydScript, so perhaps it makes sense to just default to namespaces and let one use html directly when that's not the intent (or maybe add an anti-module keyword similar to how nonlocal tells the compiler not to limit the variable to local scope, `nonlocal *` at the top of the file?).

**Comment by kovidgoyal** [comment]
Well all you have to do in that case is in Constants.py, do 

```
window.X, window.Y, windows.Z = ...
```
once. Similar to how you can do

```
__builtins__['X'] = whatever
```

in python. But, I really strongly encourage you not do this. It *will* bite you in the ass sooner or later. Instead define a macro in vim to add the import statement to a file with a couple of keystrokes. Or better use Object.defineProperty so you can access the points as named attributes, like a python namedtuple.

**Comment by hartsantler** [comment]
@kovidgoyal adding a macro in vim is not a solution that works for everybody, so dont even mention it.

**Comment by kovidgoyal** [comment]
@hartsantler Kindly refrain from telling other people what they can and can not mention. Or you will get stomped on, hard. And spend some time doing some actual research, before you mouth of on the internet. If you did you would find that @atsepkov, to whom I was responding, uses vim as his editor and has in fact written an entire vim plugin to make it work better with RS.

**Comment by atsepkov** [comment]
Guys, let's not start a fight here. I think @hartsantler was only saying that editor macros is not a solution that scales for the rest of the community, and I agree with that. Moreover, the main benefit of Python is readability, having a macro that adds all 100 of my constants into a file may help with writing the code, but definitely not with readability - which is what we're after in the end. Also, should you wish to remove one of your constants after importing it into 50 files with that macro, then it will really bite you in the ass.

Also, as you mention, `window.X = ...` for every variable is not a clean way of making the variable accessible in every scope - which is exactly why I want to allow for a way to preserve the capability of the current import system, because that's not what it does. This is what the current system actually generates, which is a huge difference because we're not actually leaking anything outside:

    (function(){
        var X = 0;
        var Y = 1;

        // your modules and other stuff here
        ...
    )();

**Comment by kovidgoyal** [comment]
I'm sorry, but we just have to agree to disagree here. IMO supporting the ability to pollute the global namespace of all your code, just to save a little typing is simply wrong. 

You claim it increases readability, I agree it does -- in the local context -- at the cost of isolation, modularization, global state, debuggability and hence long term maintainability. And having been the principal maintainer of a code base of half a million lines of code with over a hundred contributors over nearly a decade, I know whereof I speak.

But, hey I am no dictator, so if you really insist, I wont stand in your way. You can easily achive this by having the compiler generate a single varaible it places in the outermost context and passes it as this to all the functions enclosing each module.

Then when you want to export a symbol and make it available to all your modules without using window, just do this:

this.X = whatever;

Now in all modules you can refer to X directly.

this.X, this.Y = whatever

**Comment by kovidgoyal** [comment]
Actually I take that back, my solution in the previous post wont work. Since JS does not look up the this object for variable references. 

Instead a better solution for polluting the global namespace is to use the already existing ```nonlocal``` keyword. If the compiler detects the use of nonlocal at the outermost scope of a module, it can move the declaration of the variable from the module scope to the outermost (toplevel) scope. Then it will be available in all modules under that name.

**Comment by kovidgoyal** [comment]
And to suit actions to words, here is the implementation:
https://github.com/kovidgoyal/RapydScript/commit/1af112af5116c65a79fc928fe4e1f7af1290f857

Now you can simply use 

```
nonlocal X
X = whatever
```

in the module where X should be defined and in all other modules just use X as a global name.

And heaven help you :)

**Comment by atsepkov** [comment]
Thanks for addressing this use case. Also, I get it, you don't like this pattern. But there is no need for the resentment, or repeatedly and subjectively referring to this pattern as "polluting global namespace". You're not the only one with over a decade of experience in software development, there is no right or wrong answer in language design, only heuristics we've adopted throughout the years based on prior experience.

The issues you describe will only arise if developer willingly misuses this pattern, overriding what was intended to be a constant. The intent of compiler is to prevent developer from making errors, not from being malicious. You could easily shoot yourself in the foot in Python in a similar way, if you wanted to:

    True = False
    if True:
        print "Why won't this print?"

**Comment by atsepkov** [comment]
Also, your import test file states a license of GPLv3. It (and other locations stating GPL) will need to be changed to BSD to be compliant with this repo, otherwise I can't accept the changes. GPL license is a big no-no for paranoid legal departments in companies, who seem oblivious to the fact that their generated content is not bound by GPL terms as well. I've been through this before, and one of the members convinced me to switch to BSD, especially since all other compilers we're effectively competing with (CoffeeScript, etc.) are also BSD/MIT. In other words, having any part of the compiler be GPL prior to its widespread adoption is suicidal to its future.

**Comment by kovidgoyal** [comment]
This pattern is not something that can only cause problem with deliberate misuse, it is something that can be accidentally misused. This is particularly the case in a large codebase with multiple contributors. 

Take your own example of using global constants as array indices. Suppose a few years later you no longer maintain this codebase and someone else happens to add a new section to it, and does not realize that you have used X, Y and Z as global variables, in a section of the codebase that is mature and no one looks at any more. Now he also has the idea that using global variables as array indices is a great way to save some typing and increase readability. Only he decides that instead of X, Y and Z = 0, 1, 2 he wants X, Y and Z = 2, 1 0.

There you go, hard to debug logic bugs. And I'm sorry, but I dont subscribe to the notion that everything is subjective and there is no right and wrong answer. When someone asks you for a feature in RS and you decline them on the grounds that it is not a good fit, you are effectively saying some things are bad. There is no way to design anything, most especially software, without making judgments about what is right and wrong. 

It is my judgment that using global variables is bad. You disagree, fine, that is your right, and like I said, lets agree to disagree. Since this is your project, I am willing to accommodate your desires in code I contribute to you. But that does not change my right to state my opinion of this design pattern. I apologize if my doing so upsets you, that is not my intention.

As for the GPL -- sure, it's your project you get to choose the license. I just have GPL headers inserted automatically by my editor in all new files, and i sometimes forget to change them manually. If you ever notice that again, just point it out and I will change it. I will point out that you have GPL licensed code in your examples folder. If you are concerned about paranoid legal departments, you'd best remove it. In fact, I would suggest removing the examples folder altogether and making it into a separate repo. The Readme.md provides enough of an introduction for new users.

**Comment by kovidgoyal** [comment]
FYI, the import system is finished. Aliasing and incremental compilation are both done.

**Comment by joystein** [comment]
+1 FWIW, this was what made me start using RapydScript after having followed it for a while. I'm currently using @kovidgoyals' fork. It would be wonderful if at least some of the new features of that fork could be merged back into the official repo.

**Comment by atsepkov** [comment]
@joystein I'll be merging the changes shortly. I'm unfortunately only able to work on this towards weekends, I tried merging the changes last week but wanted to resolve the licensing issue first. Kovid's fork also broke some standard libraries (math.pyj, random.pyj, etc.) that I will need to fix before adding it to official fork.

Also, @kovidgoyal , your stance doesn't upset me. Your attitude towards those who don't share your stance does. Let's not dwell on this anymore.

As far as the problem you describe, I see your point. But in my opinion it's a result of poor design in other areas. First of all, all global constants should be declared in the same location. Most of the time there is no need for a constant to be global (see math.PI and math.E declarations). If one of my reports submitted code with X and Y declared globally in his own module, I'd send it back for recode. And if these re-declarations exist in the same module, wrapping it in its own namespace would do nothing to mitigate the issue. An approach that would help, however, is having compiler complain if developer redeclares a variable in global scope.

**Comment by kovidgoyal** [comment]
@atsepkov Since you have said you wanted to let this go,  I am not going to respond to your last thoughts on the subject of global variables, besides re-iterating my position, which remains: *global variables are poison, to be avoided as far as possible*.

You will find a large number of changes in my fork. And there will be more in the next few days. If you need clarification on any of them, feel free to contact me. I have tried to write tests covering every change I make to the actual compiler code, but, given the paucity of the original test suite, it is quite likely that my changes have broken some things.

**Comment by atsepkov** [comment]
Thanks kovid, I'm merging the changes up to th Jun 29th commit now. I wanted a bit more time to look at the changes that follow (mainly because I'm scared of merging kwargs changes in before I understand them). What's the best way to contact you? I tried an email address from one of your other projects but it seems like you no longer use that.

**Comment by kovidgoyal** [comment]
My current email address is in the header of some of the new files I added to my fork.

**Comment by kovidgoyal** [comment]
Oh, and on being scared: I totally understand, I would to in your position :)

Once again, I apologize for presenting you with such a large intermingled set of changes, but there was no other way for me to develop them, the alternative would have been too inefficient, and I need to get back to my main job, ASAP :)

**Comment by atsepkov** [comment]
Also, you're right that I didn't include all of the stdlib in tests, there is additional "testing" in the modules themselves commented out at the bottom that I planned to move into the general test suite but forgot to do so. For example, src/lib/math.pyj:

    #import stdlib
    #print(math.ceil(4.2))
    #print(math.floor(4.2))
    #print(math.fabs(-6))
    #print(math.copysign(-5, 7))
    #print(math.factorial(4))
    #print(math.fmod(-1e100, 1e100))
    #
    #d = [0.9999999, 1, 2, 3]
    #print(sum(d), math.fsum(d))
    #print(math.isinf(5), math.isinf(Infinity))
    #print(math.modf(5.5))
    #print(math.trunc(2.6), math.trunc(-2.6))
    #print(math.exp(1e-5), math.expm1(1e-5))
    #print(math.log(10), math.log(10, 1000))
    #print(math.log1p(1e-15), math.log1p(1))
    #print(math.log10(1000), math.log(1000, 10))
    #print(math.pow(1, 0), math.pow(1, NaN), math.pow(0, 0), math.pow(NaN, 0), math.pow(4,3), math.pow(100, -2))
    #print(math.hypot(3,4))
    #print(math.acosh(2), math.asinh(1), math.atanh(0.5), math.cosh(1), math.cosh(-1), math.sinh(1), math.tanh(1))

**Comment by kovidgoyal** [comment]
FYI: There was a bug in my incremental compilation caching implementation, now fixed. The compiler also now does compile time validation of imports, saving you from import non-existent things, that you will later only discover at runtime.

Finally, the RS compiler itself is now modularized and uses the import system.

**Comment by kovidgoyal** [comment]
@atsepkov I just received an email from you and replied. This is a notification in case my reply does not reach you :)
