### ISSUE TITLE
_$rapyd$_Iterable(iterable) fails in multiframe DOM environment such as Node-Webkit

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#70]
The test  iterable instanceof Array  fails if the array has been created in another frame because the prototype chain cannot be followed. There is a solution to this problem using  Array.isArray(iterable) instead of instanceof.  I write a lot of code which runs both in Node-Webkit and a normal web environment and I often need to iterate over arrays of database rows that may have been returned from node-sqlite3 calls which run in a separate node frame.

There are several other places in baselib which use the same test for an array. I have changed them all in my working copy of baselib but _$rapyd$_Iterable is the only case where I have observed the problem and seen that the solution works.

There is a relevant discussion in
http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/

function deep_eq(a, b) in stdlib also uses instanceof Array in a similar way and is probably vulnerable to the same problem but I have not used it so far.

**Comment by kovidgoyal** [comment]
I have changed all RS code to explicitly use Array.isArray instead of isinstance() in my fork. isinstance() itself needs to be fixed, but I left that alone as I also want it to handle multiple arguments and an array passed as a single argument, to make its behavior match python.

**Comment by atsepkov** [comment]
Yes, I'm aware of this `instanceof` limitation but ignored it in my initial implementation because cross-frame JavaScript didn't seem as a common use pattern. I don't mind changing baselib checks to `isArray`, but instanceof is also used to check inheritance, which I don't want to break.

Here are a few solutions to the problem, let me know if you have a preference:

1. Update existing code in baselib/stdlib, changing all occurrences of `isinstance(*, Array)` to `Array.isArray(*)` and stop there.
2. Tweak the compiler to auto-compile the above pattern into `isArray` automatically, just like we already optimize `for * in range(len(*))` loops into basic JS loops. The potential side-effect here is inability to handle your own iterable type that inherits from Array the same way - that will fallback to regular `instanceof` check.
3. Leave the compiler as is, but inform the users about this gotcha in the wiki. Users wanting to avoid the issue can recast the structure back into an array that will be detected locally as follows: `a = Array().concat(a)`
4. Compile `isinstance` into something with more overhead rather than using `instanceof`. I'm not a fan of this approach unless you can show me significant advantage and prove that overhead is negligible if this occurs inside a loop.

**Comment by kovidgoyal** [comment]
I would be in favor of having the compiler do the following:

Compile isinstance(obj, Array) to Array.isArray(obj)

Leave isinstance(obj, AnythingElse) as obj instanceof AnythingElse

That way the only performance hit is if you are checking for an Array, and that is unavoidable because of the nature of javascript. Hand written JS would also have to do the same thing to be robust.

**Comment by jpcharlesworth** [comment]
My primary aim is to avoid having to modify a considerable body of existing code. Therefore I would not be in favour of option 3. I do not have evidence to justify option 4. Options 1 and 2 are both acceptable with a slight preference for option 2. The limitation on classes inheriting from Array is unlikely to be a real issue in my code.

**Comment by jpcharlesworth** [comment]
The problem no longer arises since the code was modified some time ago to use Array.isArray(iterable). If the discussion of the shortcomings of isinstance is still relevant it should be in another issue.
