### ISSUE TITLE
RS dict literals behave like JavaScript not python

### ISSUE THREAD

**Issue by kovidgoyal** [atsepkov/RapydScript#75]
This has several consequences that are surprising to python developers:

1. No support for expressions as dictionary keys, for example:
```py
{mykey():2} --> error in RS
```

2. Variable names, when used as dictionary keys are silently converted to strings
```py
a = 1
{a:1} --> {'a':1} in RS but {1:1} in python. It should give {'1':1} in RS
```

This is fixed in my fork. But note, that this change is backwards incompatible. However, you can use the RS linter, also in my fork, to easily find all locations where you need to change
``{some_string:}`` to ``{'some_string':}``

**Comment by hartsantler** [comment]
It makes sense to support `{ mykey() : 2 }` because the transpiler can assume in this case that the user wants a generated key from the expression and not literally the string `"makekey()"`.

However to be consistent with javascript in general, the form `{a:1}` should not be changed to conform to Python behavior.  This is why the project is called RapydScript, and not "PythonX".  

The fact is when using RapydScript the user is going to be interfacing with a large amounts of JavaScript, so they can not avoid learning how JavaScript works.

Interfacing with JavaScript also means generating clean and human readable code, because someone may actually have to edit the translation output by hand.  If too much magic is injected into the translation output to make it behave like regular Pytho, then it hurts readability as well as performance.

**Comment by kovidgoyal** [comment]
There is no magic. Indeed, converting {a:1} -> {'a':1} as javascript does is magic. And what's more it is unexpected magic that leads to hard to debug runtime bugs. Furthermore, changing dict literals to work like python instead of javascript does not prevent you from interfacing with javascript in any way, whatsoever. The only thing it prevents you from doing is copy-pasting javascript code and having it be valid RapydScript code, which you cannot do anyway for other reasons.

**Comment by hartsantler** [comment]
The problem interfacing with JS is when someone has to read the output, and sees something like this, a function that takes a dict literal:
```javascript
somefunc( __construct_dict__( [[key1,value1], [key2,vaue2]] ) );
```

They are going to say the transpiler is generating ugly and hard to read code, because they are expecting clean translation to this:
```javascript
somefunc( {key1: value1, key2: value2} );
```

**Comment by kovidgoyal** [comment]
Why dont you actually try it first? If you did you would see that the generated JavaScript would actually look like:

somefunc({"key1":value1, "key2":value2})

**Comment by hartsantler** [comment]
no need to even try it, because this will not work in the real world where people are going to need to copy and paste from javascript source and convert it into RapydScript.  When using samples and examples from other javascript libraries, those will all of course be in javascript.  The ecosystem is js, and RapydScript fits well into that already.

**Comment by kovidgoyal** [comment]
ROFL So as a I address each of your objections, you come up with a new one. I'm done wasting my time with you. Go read the previous posts in this thread, and see how your latest objection is already addressed there. 

As a matter of fact given that this project seems to be dead in any case, I am done wasting my time here, period. I will continue to develop and use my own version of RapydScript.

**Comment by atsepkov** [comment]
The project isn't dead, Kovid and I don't appreciate you spreading misinformation. You've thrown a lot of incompatible changes, I've merged some but not others because as stated before, I'm not replicating Python exactly, and I don't like changes that detract from readability or performance. I don't want RapydScript developers to be at a disadvantage to native JavaScript developers, I don't want to repeat the same mistakes as Pyjamas. Additionally, I can't break backwards compatibility on a whim, I myself have several projects written in RapydScript and so does the community.

@hartsantler maintains a similar project (Rusthon). Both him and myself ask ourselves "does this feature make sense in JavaScript world, does it enhance developers ability to produce good JavaScript?" rather than "can I replicate this Python feature in JavaScript?" when we implement something new. Regardless of what kind of "magic" JavaScript does on the background, that magic is now the baseline, we build our patterns around it.

I appreciate your contributions but realize that our goals here are not the same. You're free to continue with your fork, but please don't shit on the project that gave you your roots.
