### ISSUE TITLE
ValueError not defined despite importing it from stdlib_common

### ISSUE THREAD

**Issue by coryell** [atsepkov/RapydScript#80]
Even though `ValueError` is imported from `stdlib_common`

    from stdlib_common import ValueError
you get a `ReferenceError` when a `ValueError` should be raised.

For example:

    val = ValueError("Test")
    print(val.name, val.message) # prints "ValueError Test"
    print([1,2,3].index(3)) # prints "2"
    print([1,2,3].index(4)) # raises "Uncaught ReferenceError: ValueError is not defined"

**Comment by atsepkov** [comment]
This broke as a result of the changes to the import mechanism from kovid's fork. I have already fixed a similar issue in math, re, random and a few other libs, but this one will be more problematic because of how stdlib exports interact with the language. Kovid addressed the issue in his fork by moving these into baselib, and I think I may end up doing the same. Otherwise, I'll need an alternative import mechanism for cases like this.

**Comment by atsepkov** [comment]
ValueError is now part of baselib, you no longer need to include the stdlib for it
