### ISSUE TITLE
destructuring assignments don't work

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#84]
#### context

```
#! /usr/bin/python
from __future__ import print_function
(x, y) = [123, 'x']
print(x, y)
```

The LHS here is called a destructuring assignment.

#### Desired and Expected Behavior (standard python)

```
123 x
```
#### Observed behavior (firefox)

```
Runtime error: 'assignment to undeclared variable x'
From __$main  parent: 207  runline: 246  char: 17  cmpline: 40  pyline: -3
>>> /*    28 */     ▼[x,y,] = [123,"x",];
From __func  parent: 207  runline: 209  char: 178  cmpline: 3  pyline: undefined
>>> ⊕__g.frame;__g.frame=frame;try{▼body()}catch(e){__g.setEF(e,frame.prev)⊕
From main  parent: 207  runline: 227  char: 1  cmpline: 21  pyline: undefined
```

This is fixable by fiddling with the python source, but there is bigger game afoot:

#### Observed behavior (chrome)

```
Unable to load compiled code.... thrown errmsg: (Invalid left-hand side in assignment) file: (undefined) line: (undefined)
(program):215 ReferenceError: Invalid left-hand side in assignment
    at driver (eval at doit (file:///mnt/more/jsd/physics/glorpy-play.html:84:25), <anonymous>:207:25)
    at doit (file:///mnt/more/jsd/physics/glorpy-play.html:93:7)
    at onload (file:///mnt/more/jsd/physics/glorpy-play.html:114:115)
```

The problem is, the RS compiler implements destructuring in a way that does not work on chrome, IE, or opera.   Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

Maybe in a few years all browsers will support something like this.  However, in the meantime, the compiler should generate code to implement destructuring in terms of features that are reliably available at runtime.   It already knows how to do analogous things;  see e.g. the generated code in issue #37

Maybe the "direct" implementation could be available as an optional optimization, but for right now reliability and portability should take precedence over optimization.

**Comment by kovidgoyal** [comment]
This is fixed in my fork, but note that the syntax for destructuring assignments in RS does ont include the parentheses, since RS has no tuples. You just do

x, y = [1, 2]

you only need parentheses for recursive destructuring

x, (y, z) = [1, [2, 3]]

**Comment by JohnDenker** [comment]
I am using a freshly-pulled copy of the github repo:
```
      bin/rapydscript --version
      rapydscript 0.3.6
```
If that's not the right version, please clarify how to obtain a better version.

If that is a current-enough version, it appears there is still an issue to discuss:

* The example that I gave, including the parentheses on the LHS, works fine under standard python, including python2.7, python3.4, ipython, and ipython3.

* The version without parentheses is also allowed.  We agree that **IF** the parentheses are left off, rapydscript generates usable code.

* My point remains, if the parentheses are included, as in the given example, RS generates code that works only under firefox ... not under chrome, ie, opera, or nodejs.
```
var __name__ = "__main__";[x,y]=[123,"x"];
```

**Comment by kovidgoyal** [comment]
My **fork** https://github.com/kovidgoyal/rapydscript-ng

**Comment by kovidgoyal** [comment]
And yeah, using outermost parentheses in RS will not work. And sure that is legal in python, it isn't in RS. There are many subtle (and not so subtle) differences like this one between RS and Python, read the gotchas section of the readme in my fork.

This should be a relatively easy fix to have the RS compiler detect and handle this situation, but, personally speaking, since I never use outermost parentheses in python for destructuring assignments, my motivation level to fix it in RS is not very high. Patches are welcome :)

**Comment by atsepkov** [comment]
Aside from lack of tuples, which @kovidgoyal already mentioned, the use case you mention works in the master fork too (I just tested this in the REPL):

    x, y = 123, 'x'
    x, y = [123, 'x']
    [x, y] = [123, 'x']

As for the use case you mention, that is broken in both forks as well. What kovid's fork does better, is nesting of them, which is not what has been asked in this particular question.

**Comment by atsepkov** [comment]
Also, @kovidgoyal I appreciate your effort in improving the language (and you know I've been merging features back) but trying to take RS users from the main version into your fork with every issue/request by claiming your fork is superior is a bit unethical, don't you think? Especially when you claim that your fork wasn't intended as a hostile fork. I don't think either of us has anything to gain from community segmentation.

@JohnDenker to clarify, Kovid forked the project a few months back and has been very active in improving the language. Many of the features he worked on (REPL, linter) are already in the main fork. In the end of the day both forks are pretty similar (although Kovid's fork is a somewhat ahead since I lack the free time to work on this and it's been hard trying to replicate functionality without having actual pull requests). Both forks aim to provide Pythonic consistency on top of crazy JavaScript world without sacrificing performance (something many other Python-in-a-browser projects failed at), but we do have a few disagreements here and there about what should and shouldn't be in the language and/or how to implement a certain feature, hence the two different forks.

**Comment by kovidgoyal** [comment]
@atsepkov I am not trying to steal users, I am just pointing out, *mainly to you* that the fix already exists, so you dont have to re-invent the wheel each time. If you would rather I dont do that, just say so, and I am happy to stop commenting on bug reports in your repo. No skin off my nose.

And note that I have added a fix for using outermost parentheses to my fork, it was literally a three line fix :) https://github.com/kovidgoyal/rapydscript-ng/commit/41ab9feb2a0bc39ea6e2397dbc4dd407fc13e14e

**Comment by atsepkov** [comment]
Thanks, it was more to do with the following comment by John:

    If that's not the right version, please clarify how to obtain a better version.

And the following authoritative answer:

    My fork https://github.com/kovidgoyal/rapydscript-ng

If it wasn't intended as such, I apologize. I was simply pointing that "better" version is subjective, is Linux Mint better than Ubuntu in every way? Moreover for that particular bug, both versions had it at the time of the writing.

**Comment by kovidgoyal** [comment]
I didn't mean to imply my fork was better. I was just clarifying to the OP what he had to do to get hold of my fork, since he seemed to be unclear on that.

As you said, we disagree about the way certain things should work, that does not mean that one approach is necessarily better than the other, just different :)
