### ISSUE TITLE
#! hash-bang comment corrupts output

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#90]
Consider any python program that begins with the conventional hash-bang directive:
```
    #! /usr/bin/python
```
This is accepted just fine by python2.7, python3.4, and various flavors of ipython.  As far as the python language is concerned, it's just a comment.

However, RS generates incorrect output.  The output begins
```
#! /usr/bin/pythonvar _$rapyd$_iterator_symbol=    .......
```

* Evidently the comment is being copied to the output.  This has no chance of being correct.

* BTW FWIW, the fact that it is missing a newline (or other separator) at the end just compounds the error, making it somewhat harder to debug.

* The -ng fork exhibits the same bug.

#### Suggestion
Just treat it as an ordinary comment.  Don't send any part of it to the output file.

**Comment by atsepkov** [comment]
Thanks for finding this.

The newline is missing because compression in RapydScript naively strips all newlines (which in all other cases are not significant). If you use `-p` compilation flag, this will work as expected - the real bug is the missing newline, not that this shouldn't be output to terminal.

In fact, the hash-bang directive is used even in languages like JavaScript, which use a different character to signify a comment - take a look at `bin/rapydscript` file, it uses this directive to trigger itself via node.

**Comment by JohnDenker** [comment]
I don't understand why it should ever be copied to the output.  The hashbang construct is used to specify the interpreter ... and the output cannot possibly use the same interpreter as the input.

**Comment by JohnDenker** [comment]
If somebody wants to specify **some other** mechanism whereby a meaningful hashbang expression gets sent to the output, that would be great ... but just copying it from the input doesn't seem like the right idea.

**Comment by atsepkov** [comment]
Perhaps, the reason it exists in the language to begin with is based on the assumption that the user may want to specify the interpreter in the code. But you are correct that this implies the same interpreter for input as for output, which is not the case.

**Comment by JohnDenker** [comment]
I suggest that letting the hashbang line produce no output at all is a perfectly reasonable solution.  Just treat it as an ordinary comment.

Users can easily add a hashbang directive (or anything else they want) to the compiler output.  There are at least a dozen ways of using standard unix tools to postprocess the output.

Many users don't want a hashbang directive anyway.  This includes those who are incorporating the compiled code into a larger project.

**Comment by kovidgoyal** [comment]
Hashbangs are almost certainly present only as a legacy from uglifyjs, which is what the RS compiler is based on. They made sense for uglifyjs since the input and output are both JS. They dont for RS.

https://github.com/kovidgoyal/rapydscript-ng/commit/1332a327ff2a08040aceac36cd9ca352d8375a3f

@JohnDenker Incidentally, you dont need to pipe output to node to execute it, just use rs -x
